kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-secrets-integrator.fullname" . }}
  labels:
    {{- include "vault-secrets-integrator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["secrets"]
    verbs: ["*"]
