kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-secrets-integrator.fullname" . }}
  labels:
    {{- include "vault-secrets-integrator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-secrets-integrator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-secrets-integrator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
