kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nfs-provisioner.fullname" . }}
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nfs-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nfs-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
