kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nfs-provisioner.fullname" . }}
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
